### PR TITLE
Fix some rust.ungram inconsistencies

### PR DESCRIPTION
**Pull request by Veykril**

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
This broke rust-analyzer (the visibility removal for macro_rules) and I had to fix that as part of rust-analyzer/rust-analyzer#11532 😢.

**Comment by Veykril** [comment]
Oh I'm sorry, I should've checked that prior. But seeing this now I believe removing that was an error from my part, as this is valid syntax, but invalid semantically. So we should revert that one change again.

**Comment by ChayimFriedman2** [comment]
At least this helped me reveal a bug where we changed the visibility of macro in the "Extract module" assist :)

https://github.com/rust-analyzer/rust-analyzer/blob/6b55d2f10aea2f38be83693b55e8dcf771335233/crates/ide_assists/src/handlers/extract_module.rs#L784

https://user-images.githubusercontent.com/24700207/155522440-24692077-bbce-48f7-93d6-d08e4f258233.mp4

**Pull request merged**
