### PR TITLE
Revert macro changes

### PR DESCRIPTION
**Pull request by jonas-schievink**
I came up with a less invasive solution for https://github.com/rust-analyzer/rust-analyzer/issues/7717

bors r+

### CODE REVIEW

**Comment by lnicola** [comment]
Might want to bump the version, too.

**Comment by Veykril** [comment]
Can be done together with #29 I guess?

**Comment by matklad** [comment]
Hm, I the previous version actually made more sense?

**Comment by matklad** [comment]
I do think that ungrammar's shape should be "reasonable", and independent of impl details of rust-analyzer. But I am still undecided if an extra wrapped around macro calls is reasnable...

**Pull request merged**
