### PR TITLE
Add `MacroDef` for "Macros 2.0"

### PR DESCRIPTION
**Pull request by jonas-schievink**

### CODE REVIEW

**Comment by matklad** [comment]
Maybe just Macro?

**Comment by jonas-schievink** [comment]
I was going to use that for

```rust
pub enum Macro {
    MacroRules(ast::MacroRules),
    MacroDef(ast::MacroDef),
}
```

but yeah, the naming isn't really ideal

**Comment by jonas-schievink** [comment]
Oh, we already have parsing support for this since https://github.com/rust-analyzer/rust-analyzer/pull/2628, so it should probably remaing `MacroDef` here to match the existing work

**Comment by matklad** [comment]
Ok, lets keep it as Def for now

bors r+

Though, it might still make sense to get rid of Def. We used to have Def suffix on everythign, but removing it a while back made the code read better.

**Pull request merged**
